export interface Product {
  id: number | string;
  name: string;
  price: number;
  originalPrice: number;
  discount: number;
  image: string;
  rating: number;
  sold: number;
  category: string;
  isMall?: boolean;
  stock?: number;
  seller?: string;
  description?: string;
}

export const CATEGORIES = [
  { id: 1, name: "Thời Trang Nam", icon: "👕" },
  { id: 2, name: "Điện Thoại & Phụ Kiện", icon: "📱" },
  { id: 3, name: "Thiết Bị Điện Tử", icon: "💻" },
  { id: 4, name: "Máy Tính & Laptop", icon: "🖥️" },
  { id: 5, name: "Máy Ảnh - Máy Quay Phim", icon: "📷" },
  { id: 6, name: "Đồng Hồ", icon: "⌚" },
  { id: 7, name: "Giày Dép Nam", icon: "👞" },
  { id: 8, name: "Thiết Bị Gia Dụng", icon: "🔌" },
  { id: 9, name: "Thể Thao & Du Lịch", icon: "⚽" },
  { id: 10, name: "Ô Tô - Xe Máy - Xe Đạp", icon: "🚗" },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Áo thun nam ngắn tay cổ tròn cotton 100% cao cấp co giãn thoáng khí",
    price: 89000,
    originalPrice: 150000,
    discount: 41,
    image: "https://picsum.photos/seed/p1/400/400",
    rating: 4.8,
    sold: 12500,
    category: "Thời Trang Nam",
    isMall: true,
  },
  {
    id: 2,
    name: "Tai nghe Bluetooth không dây thế hệ mới âm thanh Hifi chống ồn",
    price: 250000,
    originalPrice: 450000,
    discount: 44,
    image: "https://picsum.photos/seed/p2/400/400",
    rating: 4.9,
    sold: 5400,
    category: "Thiết Bị Điện Tử",
  },
  {
    id: 3,
    name: "Sạc dự phòng 20000mAh sạc nhanh 22.5W dung lượng chuẩn",
    price: 189000,
    originalPrice: 320000,
    discount: 41,
    image: "https://picsum.photos/seed/p3/400/400",
    rating: 4.7,
    sold: 8900,
    category: "Điện Thoại & Phụ Kiện",
    isMall: true,
  },
  {
    id: 4,
    name: "Giày Sneaker nam nữ thể thao phong cách Hàn Quốc bền đẹp",
    price: 120000,
    originalPrice: 250000,
    discount: 52,
    image: "https://picsum.photos/seed/p4/400/400",
    rating: 4.6,
    sold: 15200,
    category: "Giày Dép Nam",
  },
  {
    id: 5,
    name: "Bàn phím cơ không dây layout 75% có LED RGB hotswap",
    price: 599000,
    originalPrice: 850000,
    discount: 30,
    image: "https://picsum.photos/seed/p5/400/400",
    rating: 4.9,
    sold: 2100,
    category: "Máy Tính & Laptop",
  },
  {
    id: 6,
    name: "Chuột Gaming không dây siêu nhẹ cảm biến 26k DPI",
    price: 450000,
    originalPrice: 650000,
    discount: 31,
    image: "https://picsum.photos/seed/p6/400/400",
    rating: 4.8,
    sold: 3500,
    category: "Máy Tính & Laptop",
    isMall: true,
  },
  {
    id: 7,
    name: "iPhone 15 Pro Max 256GB - Hàng chính hãng VN/A",
    price: 29990000,
    originalPrice: 34990000,
    discount: 14,
    image: "https://picsum.photos/seed/iphone15pm/400/400",
    rating: 4.9,
    sold: 1520,
    category: "Điện Thoại & Phụ Kiện",
    isMall: true,
    stock: 120,
  },
  {
    id: 8,
    name: "MacBook Air M2 13 inch 256GB 2024",
    price: 24990000,
    originalPrice: 29990000,
    discount: 17,
    image: "https://picsum.photos/seed/macbookairm2/400/400",
    rating: 4.8,
    sold: 830,
    category: "Máy Tính & Laptop",
    isMall: true,
    stock: 60,
  },
  {
    id: 9,
    name: "Tai nghe Bluetooth AirPods Pro 2 MagSafe",
    price: 5590000,
    originalPrice: 6490000,
    discount: 14,
    image: "https://picsum.photos/seed/airpodspro2/400/400",
    rating: 4.9,
    sold: 2350,
    category: "Thiết Bị Điện Tử",
    isMall: true,
    stock: 200,
  },
  {
    id: 10,
    name: "Chuột Logitech MX Master 3S Không dây",
    price: 1990000,
    originalPrice: 2490000,
    discount: 20,
    image: "https://picsum.photos/seed/mxmaster3s/400/400",
    rating: 4.9,
    sold: 640,
    category: "Thiết Bị Điện Tử",
    isMall: false,
    stock: 80,
  },
  {
    id: 11,
    name: "Bàn phím cơ Keychron K2 Version 2 RGB",
    price: 1890000,
    originalPrice: 2290000,
    discount: 17,
    image: "https://picsum.photos/seed/keychronk2/400/400",
    rating: 4.7,
    sold: 410,
    category: "Thiết Bị Điện Tử",
    isMall: false,
    stock: 90,
  },
  {
    id: 12,
    name: "Áo thun Unisex Oversize Basic",
    price: 159000,
    originalPrice: 199000,
    discount: 20,
    image: "https://picsum.photos/seed/tshirtoversize/400/400",
    rating: 4.6,
    sold: 980,
    category: "Thời Trang Nam",
    isMall: false,
    stock: 300,
  },
  {
    id: 13,
    name: "Giày Sneaker Trắng Classic",
    price: 399000,
    originalPrice: 499000,
    discount: 20,
    image: "https://picsum.photos/seed/sneakerclassic/400/400",
    rating: 4.7,
    sold: 720,
    category: "Giày Dép Nam",
    isMall: false,
    stock: 150,
  },
];
